---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
  namespace: egs-doctalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
      - name: appointments
        image: docker.io/vdfijhnf8yerf87hgti/egs-doctalk-appoint:latest
        imagePullPolicy: Always
        env:
        - name: DOTNET_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:5186"
        - name: DATABASE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: egs-doctalk-secrets
              key: APPOINTMENTS_DATABASE_CONNECTION_STRING
        ports:
        - containerPort: 5186
      - name: appointments-db
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: egs-doctalk-secrets
              key: APPOINTMENTS_DATABASE_PASSWORD
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        ports:
        - containerPort: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: egs-doctalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/vdfijhnf8yerf87hgti/egs-doctalk-backend:latest
        imagePullPolicy: Always
        env:
        - name: DOTNET_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:5285"
        - name: DATABASE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: egs-doctalk-secrets
              key: BACKEND_DATABASE_CONNECTION_STRING
        - name: APPOINTMENT_SERVICE_BASE_URL
          value: "http://appointments-service:80/v1"
        - name: AUTH_SERVICE_BASE_URL
          value: "https://app-egs-doctalk.duckdns.org"
        - name: NOTIFICATION_SERVICE_BASE_URL
          value: "http://notification-svc:80/v1"
        - name: WEBRTC_SERVICE_BASE_URL
          value: "http://webrtc-service:80"
        - name: FRONTEND_HOME_URL
          value: "https://app-egs-doctalk.duckdns.org"
        ports:
        - containerPort: 5285
      - name: backend-db
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: egs-doctalk-secrets
              key: BACKEND_DATABASE_PASSWORD
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        ports:
        - containerPort: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  namespace: egs-doctalk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication-api
  template:
    metadata:
      labels:
        app: authentication-api
    spec:
      containers:
        - name: authentication-svc
          image: docker.io/vdfijhnf8yerf87hgti/egs-doctalk-auth:latest
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "5800"
          ports:
            - containerPort: 5800
      dnsConfig:
        options:
          - name: ndots
            value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: egs-doctalk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      containers:
      - name: notification-api
        image: docker.io/vdfijhnf8yerf87hgti/egs-doctalk-notif:latest
        imagePullPolicy: Always
        env:
        - name: BIND_PORT
          value: '3030'
        - name: BIND_ADDR
          value: '0.0.0.0'
        ports:
        - containerPort: 3030
      dnsConfig:
        options:
          - name: ndots
            value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrtc-deployment
  namespace: egs-doctalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webrtc
  template:
    metadata:
      labels:
        app: webrtc
    spec:
      containers:
      - name: webrtc
        image: docker.io/vdfijhnf8yerf87hgti/egs-doctalk-webrtc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peerjs-deployment
  namespace: egs-doctalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peerjs
  template:
    metadata:
      labels:
        app: peerjs
    spec:
      containers:
      - name: peerjs
        image: docker.io/vdfijhnf8yerf87hgti/egs-doctalk-peerjs:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: egs-doctalk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/vdfijhnf8yerf87hgti/egs-doctalk-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: appointments-service
  namespace: egs-doctalk
spec:
  ports:
  - port: 80
    targetPort: 5186
  selector:
    app: appointments
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: egs-doctalk
spec:
  ports:
  - port: 80
    targetPort: 5285
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-svc
  namespace: egs-doctalk
spec:
  selector:
    app: authentication-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5800
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  namespace: egs-doctalk
spec:
  selector:
    app: notification-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: webrtc-service
  namespace: egs-doctalk
spec:
  ports:
  - port: 80
    targetPort: 3300
  selector:
    app: webrtc
---
apiVersion: v1
kind: Service
metadata:
  name: peerjs-service
  namespace: egs-doctalk
spec:
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: peerjs
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: egs-doctalk
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: egs-doctalk-ingress-k3s
  namespace: egs-doctalk
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: app-egs-doctalk.duckdns.org
    http:
      paths:
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port: 
              number: 80
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: authentication-svc
            port: 
              number: 80
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: authentication-svc
            port: 
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port: 
              number: 80
      - path: /peerjs
        pathType: Prefix
        backend:
          service:
            name: peerjs-service
            port: 
              number: 80
      - path: /socket.io
        pathType: Prefix
        backend:
          service:
            name: webrtc-service
            port: 
              number: 80