version: "3.9"
services:
  appointment_service:
    build: 
      dockerfile: AppointmentService/AppointmentService/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5186

      - DATABASE_CONNECTION_STRING=Server=appointment-db;User=sa;Password=Password1;TrustServerCertificate=True
    ports:
      - "5186:5186"
    depends_on: 
      - appointment-db
    networks:
      appointment-db-internal:
        ipv4_address: 10.0.1.2
      backend-appointment-internal:
        ipv4_address: 10.0.3.3
  appointment-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      appointment-db-internal:
        ipv4_address: 10.0.1.3
  backend:
    build: 
      dockerfile: EGS-Backend/Backend/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7000;http://+:5285
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      
      - DATABASE_CONNECTION_STRING=Server=backend-db;User=sa;Password=Password1;TrustServerCertificate=True
      - APPOINTMENT_SERVICE_BASE_URL=http://appointment_service:5186/v1
      - NOTIFICATION_SERVICE_BASE_URL=http://notification_service:4000/
      - AUTH_SERVICE_BASE_URL=http://localhost:5000
    ports:
      - "7000:7000"
      - "5285:5285"
    volumes:
      - ./certs:/https:ro
    depends_on: 
      - backend-db
    networks:
      default:
      backend-db-internal:
        ipv4_address: 10.0.2.2
      backend-appointment-internal:
        ipv4_address: 10.0.3.2
      notification-backend-internal:
        ipv4_address: 10.0.4.2
  backend-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      backend-db-internal:
        ipv4_address: 10.0.2.3
  notification_service:
    build:
      dockerfile: notification-service/Dockerfile.notify
    ports:
      - "4000:4000"
    networks:
      notification-backend-internal:
        ipv4_address: 10.0.4.3
  authentication_service:
    build:
      dockerfile: authentication-service/Dockerfile.auth
    ports:
      - "5000:5000"
    networks:
      default:
networks:
  appointment-db-internal:
    internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"
  backend-db-internal:
    internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/24"
  backend-appointment-internal:
    internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.3.0/24"
  notification-backend-internal:
    internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.4.0/24"